version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
      - /app/node_modules 
    depends_on:
      - mongo 
    environment:
      
      DATABASE_URL: mongodb://mongo:27017/product_db_docker 
      
    restart: unless-stopped 

  mongo:
    image: mongo:6 
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data: